### ISSUE TITLE
VMP's optimized entity tracking messing with grappling hook's collision (Grappling Hook: Restitched)

### ISSUE THREAD

**Issue by iSimilaXi** [RelativityMC/VMP-fabric#38]
**Describe the bug**
When using grappling hook with VMP's optimized entity tracking settings (enabled by default), the grappling hook's collision is inaccurate. (Float in the air, near the wall that it was supposed to landing at.)

**To Reproduce**
1. While using VMP, right click to activate the grappling hook near a wall.
2. Check the grappling hook collision.

**Expected behavior**
the grappling hook will float in the air, instead of stick to the surface of the block.

**Screenshots**
![image](https://user-images.githubusercontent.com/93301357/219865036-7c21d383-1f29-4c0b-bfea-9a8e75a0d179.png)

**Runtime info (please complete the following information):**
 - OS: Windows 10 64x
 - Minecraft version: 1.19.2
 - Mod version: 0.2.0+beta.7.28

**Other mods**
 - Grappling Hook: Restitched v1.3

**Checklist**

 - [x] I am using the official version of the mod. 
 - [ ] I tried the latest development version but the issue persists. 
 - [x] I searched for similar open issues and could not find an existing bug report on this. 

**Additional context**
- Changing use_optimized_entity_tracking to false in vmp.properties config 'fixed' the problem.
- CloudG360/grapplemod-restitched#9 (edit by moderator)

**Comment by squeeglii** [comment]
Issue tracked in my repo moved -> https://github.com/CloudG360/grapplemod-restitched/issues/1

**Comment by ishland** [comment]
Does the issue still persists on current latest devbuild?

**Comment by squeeglii** [comment]
@ishland tested with build 0.2.0+beta.7.73+1.19.4 - nope! All fixed!
Should be alright to mark this as resolved.

**Comment by ishland** [comment]
Closing as resolved.
